services:
  api-gateway:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - product-service
      - user-service
    networks:
      - app_network
networks:
  app_network:
    external: true
