services:
  # ==========================
  # API Gateway (Nginx)
  # ==========================
  api-gateway:
    build: ./api-gateway
    container_name: api_gateway
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - product-service
      - user-service
      - cart-service
      - review-service
      - order-service
    networks:
      - app_network

  # ==========================
  # Product Service (NestJS + mysql)
  # ==========================
  product-service:
    build:
      context: ./product-service
      dockerfile: dockerfile.dev
    container_name: product_service
    restart: always
    ports:
      - "3001:3001"
    environment:
      DATABASE_HOST: product-db
      DATABASE_PORT: 3306
      DATABASE_USER: root
      DATABASE_PASSWORD: APBjg7!RKa!P%t^NWd1y
      DATABASE_NAME: products
      JWT_SECRET: "@y*&0a%K%7P0t@uQ^38HN$$y4Z^PK#0zE7dem700Bbf&pC6HF$$aU^ARkE@u$$nn"
    volumes:
      - ./product-service/src:/usr/src/app/src
      - /usr/src/app/node_modules
    depends_on:
      - product-db
    networks:
      - app_network

  product-db:
    image: mysql:8
    container_name: mysql_product
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: APBjg7!RKa!P%t^NWd1y
      MYSQL_DATABASE: products
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_spanish2_ci
    volumes:
      - product_data:/var/lib/mysql
      - ./product-service/init:/docker-entrypoint-initdb.d
    networks:
      - app_network

  # ==========================
  # User Service (Express + mysql)
  # ==========================
  user-service:
    build:
      context: ./user-service
      dockerfile: dockerfile.dev
    container_name: user_service
    restart: always
    ports:
      - "3002:3002"
    environment:
      DATABASE_HOST: user-db
      DATABASE_PORT: 3306
      DATABASE_USER: root
      DATABASE_PASSWORD: Dp%mdSM^7MDr3qSQ6Cas
      DATABASE_NAME: users
      JWT_SECRET: "@y*&0a%K%7P0t@uQ^38HN$$y4Z^PK#0zE7dem700Bbf&pC6HF$$aU^ARkE@u$$nn"
    volumes:
      - ./user-service/src:/usr/src/app/src
      - /usr/src/app/node_modules
    depends_on:
      - user-db
    networks:
      - app_network

  user-db:
    image: mysql:8
    container_name: mysql_user
    restart: always
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Dp%mdSM^7MDr3qSQ6Cas
      MYSQL_DATABASE: users
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_spanish2_ci
    volumes:
      - user_data:/var/lib/mysql
      - ./user-service/init:/docker-entrypoint-initdb.d
    networks:
      - app_network

  # ==========================
  # Cart Service (Express + MongoDB)
  # ==========================
  cart-service:
    build:
      context: ./cart-service
      dockerfile: dockerfile.dev
    container_name: cart_service
    restart: always
    ports:
      - "3003:3003"
    environment:
      PORT: 3003 # Puerto donde corre Express
      MONGO_URI: mongodb://cart-db:27017/cartdb
      JWT_SECRET: "@y*&0a%K%7P0t@uQ^38HN$$y4Z^PK#0zE7dem700Bbf&pC6HF$$aU^ARkE@u$$nn"
    volumes:
      - ./cart-service/src:/usr/src/app/src
      - /usr/src/app/node_modules
    depends_on:
      - cart-db
    networks:
      - app_network

  cart-db:
    image: mongo:latest
    container_name: mongo_cart
    restart: always
    ports:
      - "3309:27017"
    volumes:
      - ./cart-service/mongo_data:/data/db
    networks:
      - app_network

  # ==========================
  # Orders Service (Express)
  # ==========================
  order-service:
    build:
      context: ./order-service
      dockerfile: dockerfile.dev
    container_name: orders_service
    restart: always
    ports:
      - "3004:3004"
    environment:
      DB_HOST: mysql_orders
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: orders_db
      PORT: 3004
      NODE_ENV: development
      JWT_SECRET: "@y*&0a%K%7P0t@uQ^38HN$$y4Z^PK#0zE7dem700Bbf&pC6HF$$aU^ARkE@u$$nn"
      JWT_EXPIRES_IN: 30d
      CORS_ORIGIN: http://localhost:3000,http://localhost:8080
    volumes:
      - ./order-service/src:/usr/src/app/src
      - /usr/src/app/node_modules
    depends_on:
      - orders-db
    networks:
      - app_network

  orders-db:
    image: mysql:8
    container_name: mysql_orders
    restart: always
    ports:
      - "3310:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: orders_db
    volumes:
      - orders_data:/var/lib/mysql
      - ./order-service/init:/docker-entrypoint-initdb.d
    networks:
      - app_network

  # ==========================
  # Reviews Service (Express)
  # ==========================
  review-service:
    build:
      context: ./review-service
      dockerfile: dockerfile.dev
    container_name: reviews_service
    restart: always
    ports:
      - "3005:3005"
    environment:
      DB_HOST: mysql_reviews
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: reviews_db
      PORT: 3005
      NODE_ENV: development
      JWT_SECRET: reviews_jwt_secret_muy_seguro_2024
      JWT_EXPIRES_IN: 30d
      CORS_ORIGIN: http://localhost:3000,http://localhost:8080
    volumes:
      - ./review-service/src:/usr/src/app/src
      - /usr/src/app/node_modules
    depends_on:
      - reviews-db
    networks:
      - app_network

  reviews-db:
    image: mysql:8
    container_name: mysql_reviews
    restart: always
    ports:
      - "3311:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: reviews_db
    volumes:
      - reviews_data:/var/lib/mysql
      - ./review-service/init:/docker-entrypoint-initdb.d
    networks:
      - app_network

# ==========================
# Volumenes
# ==========================
volumes:
  product_data:
  user_data:
  cart_data:
  orders_data:
  reviews_data:
# ==========================
# Networks
# ==========================
networks:
  app_network:
    driver: bridge
